---
appveyor.yml:
  matrix:
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23-x64
Gemfile:
  optional:
    'development':
      - gem: 'rototiller'
        version: '~> 1.0'
    ':system_tests':
      - gem: 'beaker-testmode_switcher'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'OpenTable'
      begin: 2012
      end: 2015
    - name: 'Puppet, Inc.'
      begin: 2015

# already using master branch's version
spec/spec_helper.rb:
  unmanaged: true

# includes acceptance_tests rototiller rake task added with MODULES-3373
Rakefile:
  unmanaged: true
